import { access, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { runPipeline } from '../../src/orchestrator.js';
import { createFakeCliBin } from '../helpers/fake-cli.js';

describe.sequential('pipeline with fake external CLIs', () => {
  const originalPath = process.env.PATH ?? '';
  const originalLogPath = process.env.FAKE_CLI_LOG;

  afterEach(() => {
    process.env.PATH = originalPath;
    if (originalLogPath === undefined) {
      delete process.env.FAKE_CLI_LOG;
    } else {
      process.env.FAKE_CLI_LOG = originalLogPath;
    }
  });

  it('runs planning/sync/execute/post end-to-end with fake CLIs', async () => {
    const tmpDir = await mkdtemp(path.join(os.tmpdir(), 'bemadralphy-e2e-'));
    const fakeLogPath = path.join(tmpDir, 'fake-cli.log');
    process.env.FAKE_CLI_LOG = fakeLogPath;

    const fakeBin = await createFakeCliBin(tmpDir, {
      bmad: [
        'echo "bmad $*" >> "$FAKE_CLI_LOG"',
        'dir=""',
        'out="_bmad-output"',
        'while [ "$#" -gt 0 ]; do',
        '  if [ "$1" = "--directory" ]; then',
        '    shift',
        '    dir="$1"',
        '  fi',
        '  if [ "$1" = "--output-folder" ]; then',
        '    shift',
        '    out="$1"',
        '  fi',
        '  shift',
        'done',
        'if [ -z "$dir" ]; then',
        '  dir="$(pwd)"',
        'fi',
        'out="$dir/$out"',
        'mkdir -p "$out/stories"',
        'printf "# Product Brief\\n\\nGenerated by fake bmad\\n" > "$out/product-brief.md"',
        'printf "# PRD\\n\\nGenerated by fake bmad\\n" > "$out/prd.md"',
        'printf "# Architecture\\n\\nGenerated by fake bmad\\n" > "$out/architecture.md"',
        'printf "# Epics\\n\\n### Fake Story A\\n\\nDetails\\n" > "$out/stories/epics.md"',
      ].join('\n'),
      ralphy: [
        'echo "ralphy $*" >> "$FAKE_CLI_LOG"',
        'printf "ralphy-ok\\n"',
      ].join('\n'),
      openspec: [
        'echo "openspec $*" >> "$FAKE_CLI_LOG"',
        'exit 0',
      ].join('\n'),
      bd: [
        'echo "bd $*" >> "$FAKE_CLI_LOG"',
        'case "${1:-}" in',
        '  init) exit 0 ;;',
        '  create) echo "bd-999"; exit 0 ;;',
        '  ready) printf "bd-1\\n"; exit 0 ;;',
        '  close) exit 0 ;;',
        '  update) exit 0 ;;',
        '  *) exit 0 ;;',
        'esac',
      ].join('\n'),
      git: [
        'echo "git $*" >> "$FAKE_CLI_LOG"',
        'if [ "${1:-}" = "status" ]; then',
        '  printf " M src/file.ts\\n"',
        'fi',
      ].join('\n'),
      gh: [
        'echo "gh $*" >> "$FAKE_CLI_LOG"',
        'if [ "${1:-}" = "auth" ] && [ "${2:-}" = "status" ]; then',
        '  printf "Logged in\\n"',
        'fi',
      ].join('\n'),
    });

    process.env.PATH = `${fakeBin}:${originalPath}`;

    await writeFile(path.join(tmpDir, 'idea.md'), '# Idea\n\nE2E validation project\n', 'utf-8');

    await runPipeline({
      mode: 'auto',
      maxParallel: 1,
      brownfield: false,
      createPr: true,
      dryRun: false,
      engine: 'ralphy',
      projectRoot: tmpDir,
    });

    await access(path.join(tmpDir, 'tasks.md'));
    await access(path.join(tmpDir, '.bemadralphy', 'state.yaml'));
    await access(path.join(tmpDir, '.bemadralphy', 'cost.log'));

    const tasks = await readFile(path.join(tmpDir, 'tasks.md'), 'utf-8');
    expect(tasks).toContain('Fake Story A');

    const stateYaml = await readFile(path.join(tmpDir, '.bemadralphy', 'state.yaml'), 'utf-8');
    expect(stateYaml).toContain('phase: post');

    const cliLog = await readFile(fakeLogPath, 'utf-8');
    expect(cliLog).toContain('bmad install');
    expect(cliLog).toContain('bd create');
    expect(cliLog).toContain('bd ready');
    expect(cliLog).toContain('ralphy');
    expect(cliLog).toContain('openspec validate --all --no-interactive');
    expect(cliLog).toContain('git status --short');
    expect(cliLog).toContain('gh auth status');
  });
});
